### ISSUE TITLE
Wrong type for GBAProvider

### ISSUE THREAD

**Issue by VladCuciureanu** [macabeus/react-gbajs#22]
Trying to wrap a JSX node inside GBAProvider results in the following error:
`Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.`

This is due to `GBAProvider` being typed as `FunctionComponent` instead of `FunctionComponent<{children:ReactNode}>` or similar types.

**Comment by macabeus** [comment]
Hello. Thanks for the report.
I'm now busy with other personal projects, so I'm unsure when I'll fix it.

If you can open a PR fixing it, I would be glad and faster to release a new version fixing it
